#+title: スター☆トゥインクルプリキュア
#+Date: 2019-11-19

* 何となくスタプリの歌詞が気になった

** ムゲンダイイマジネーション

「可能性＝無限大」、「想像力は無限大」というように、非物質的で非現実的なレベルでの無限性をうたっている。→実際には限界があってできないことがいっぱいあるという諦めの裏返しでしかない。カントの「形式的可能性」についての考察を無視している。とはいえ90年代に流行った無限・永遠が多少なりとも復活してきているのは嬉しい「トゥインクル、教えて♪」→星の光を叡智の光の比喩として扱っている。
	* 「人間たちはどこからくるの？」

なのだから、``子供の作り方''を問題にしているわけではない。むしろ「人間はどこから来てどこへ行くのか」というのと同じ哲学的問題である。これは人間の本性が何であるか？　という問いと同じでなければならない。〈何であるか〉は〈何をなすか〉と統一されて始めて現実的となる。「多様性があたり前にある世界」というのがテーマらしいが、多様性は統一原理なしには対立にしかならない。スタプリの世界では〈宇宙〉こそが統一原理となっている。トゥインクル 心はトゥインクル 宇宙！→宇宙の心はわたしたちだったんですね……(言いたかっただけ)
	* 「願いを叶え」

「願いを叶え」って表現にモヤモヤする……俺がおかしいのか？
願いよ、叶え！なら問題はない気がする。
「願いが叶う」の主語を人格化して命令形にしたような格好だから。

あるいは「願いを叶える」ならば自然に聞こえる。「叶える」の場合は活用は「叶えろ」にはなる。

文法上のことは知らないが、聞きなじみがないっていうあたりが引っ掛かるのだろう。
いつか「願いを叶え」が普通に聞こえる日が来るのかも知れないし、他の人には自然なのかも知れない。

** 「1+1の答えは2でいいの？」

*** $1+1=2$ に疑問をもつ人が疑問にしないこと

$1+1=2$ に疑問をもつ人というのは $=1$ や $=3$ ではダメなの？
決まり切った答え以外のものがあるのではないのか？
というようなことにすぎない。

数学の公式がいつでも同じ答えを出すのは、数学が真理をとりあつかっているからであり、しかも普遍的なレベルでとりあつかっているのだから、たとえば、1つの粘土と1つの粘土を合わせても1つの粘土にしかならない、というような反論は問題外であるというべき。
決まり切ってるということを杓子定規だと否定的にとらえる風潮があるけれども、科学にとってはそれは肯定性である。しかも常に誤差に悩まされる他の自然諸科学とは異なって数学の等式に誤差はない。

1個のリンゴと1個のみかんを合わせていくつ？という問題に「足せない…」と困る小学生の事例を出す場合もあるが、数の概念は極めて難しい問題である。
1とか2とか3とかをそれぞれ別ものとする流儀もあれば、1,2,3…と並んでいるとする流儀もあって、一言に「足し算」といっても寄せ集めるような流儀と並べて合わせていくような流儀との対立もある。
どちらか一方とするのは無理があるけれど、それらを統一するような概念はいまだ人類は獲得していないのである。
つまり、袋の中にりんごを加えいれて全部でいくつ、みたいに足すやり方と、経験値を得てレベルが一つずつ上がっていくように足すやり方とで「足し算」という概念もまた二つあるのである。


*** 読み方

「1+1=2」といっても読み方がいろいろ考えられる。

- 「1」+「1」

これは前後の「1」をそれぞれ独立させてそれらを足すと見ている。とはいえ前の1と後の1を区別したりしなかったりする流儀がともにある。

- 「1」「+1」

前の「1」に「1を加える」と見ている。この場合はいうまでもなく前の1と後の+1とは別ものである。

- 「1+1」=「2」

これは「1+1」の和として2を見ている。いいかえれば2というのは「1+1」によって生成されているといえる。カント的に言えば分析判断。

- 「1+1=2」

「1+1=2」をアプリオリに認める見方。カント的に言えば総合判断。


*** カントの純粋理性批判

「5+7=12」というのは分析判断なのか総合判断なのか？という問題提起。
分析判断とするならば証明可能であるけれど、前提をどうしたらいいのかが不明になる。
たとえば12の定義として「5+7」を採用してもいいけれど、6+6=12は別の前提をもってきて証明しなければならなくなる。5+7と6+6との恣意的な区別も問題になる。

総合判断とするならば証明不可能になる。前提で悩むことはなくなるけれど、前提どうしで不都合がないのかという問題が発生してくる。


*** ペアノの公理系

ペアノの場合は

> 「1」「+1」=1’(つまり2)

というのが基本である。

数の概念としては、1,2,3…を別ものとしながらそれらを順番に並べるというやり方をしている。
つまり1が始めにあり、$1' =2$が次に生まれ、$2'=3,3'=4,4'=5$…というように順番に生成されるものとしている。（0から始めても構わないがここでは1から始めた）

たとえば+1と+2はペアノ公理系では別ものである。
+2の場合は、+「2」であるが、+1はあくまでも「+1」である。
\begin{align}
$2+3 & =2+(2') \\
     &= (2+2)' \\
     &= (2+(1'))' \\
     &= ((2+1)')' \\
     &= ((2')')' \\
     &= ((3)')' \\
     &= (4)' \\
     &= 5$
\end{align}

のようにするのである。同じように $n+m=m+n$ も証明できるけれど自明ではない。
実は’の個数という公理系外の数字が前提されているのだけれど、明示されない。

それ以外の公理系は知らない。


