#+title: スター☆トゥインクルプリキュアの歌詞について
#+Date: 2019-11-19
#+LaTeX_header: \usepackage{amsmath}
#+OPTIONS: toc:nil num:nil author:nil creator:nil LaTeX:t ':t

* 何となくスタプリの歌詞が気になった
** ムゲンダイマジネーション
#+begin_quote
ムゲンダイマジネーション
#+end_quote

「可能性＝無限大」、「想像力は無限大」というように、非物質的で非現実的なレベルでの無限性をうたっている。
→実際には限界があってできないことがいっぱいあるという諦めの裏返しでしかない。
ついでに、カントの「形式的可能性」についての考察を無視している。
とはいえ90年代に流行った無限・永遠が多少なりとも復活してきているのは嬉しい。

#+begin_quote
「トゥインクル、教えて♪」
#+end_quote
→星の光を叡智の光の比喩として扱っている。

ところで「歪んだイマジネーション」（カッパード）「心の歪み」（テンジョウ)「闇のイマジネーション」（アイワーン）とは一体なにか。

多分無限大イマジネーションのアンチテーゼとして、有限で人と繋がれないイマジネーションのことなのだろう。
他人への理解を拒むイマジネーションは、何を求めるのか？
故郷を失い、安住の地を求めて宇宙を"乗っ取る"のがノットレイダー
他人から与えられないのならば奪いとる、ということか。

"知らないから拒絶する"のが歪んだイマジネーションであって、無限大イマジネーションは知らないから知りたい、となるのだろう。
無知ゆえの愚かな言動はよくある。けれども「 *無知は理由にはならない* 」（スピノザ）のである。
イマジネーションの歪みの根拠を「無知」とすることはできない。
けだし、全知全能の神でもないかぎり歪みのないイマジネーションはありえないことになる。

#+begin_quote
- スターの想像力のおかげでプリキュアになれたルン！ --- ミルキー
- スターがいなければみんなと楽しくお話しすることもありませんでした --- セレーネ
- ひかるのイマジネーションは、みんなを想って結びつけてくれるんだ --- ソレイユ
#+HTML: <cite> 11話プリキュアによるスター評 </cite>
#+end_quote
人と人とをつなぐのがムゲンダイマジネーションであるが、
ひかるがオリジナル星座を夜空に描くように、
人と人との絆もまたイマジネーションによってできるということなのだろう。

ノットレイダーはプリキュアの無知を責める。「お前は知らないのだ！」と。
宇宙（実は自然環境というより社会）の厳しさ、人の悪意を。
それに真っ向から反対するのがキュアスターで、「知りたい！　だって大好きだから！」
きっと、なぜ戦わなくてはいけないのか、と自問することになるのだろう……


** ニンゲンと星
#+begin_quote
「ニンゲンたちはどこからやってくるの？」
#+end_quote

一人の人間ではなく「ニンゲンたち」なのだから、"子供の作り方"を問題にしているわけではない。
むしろ「人間はどこから来てどこへ行くのか」というのと同じ哲学的問題である。
これは人間の本性が何であるか？　という問いと同じでなければならない。

〈何であるか〉は〈何をなすか〉と統一されて始めて現実的となる。
「多様性があたり前にある世界」というのがテーマらしいが、多様性は統一原理なしには対立にしかならない。
スタプリの世界では〈宇宙〉こそが統一原理となっている。

#+begin_quote
トゥインクル 心は

トゥインクル 宇宙！
#+end_quote
→宇宙の心はわたしたちだったんですね……(言いたかっただけ)

** 重箱の隅
#+begin_quote
「願いを叶え」
#+end_quote

「願いを叶え」って表現にモヤモヤする……俺がおかしいのか？
願いよ、叶え！なら問題はない気がする。
「願いが叶う」の主語を人格化して命令形にしたような格好だから。

あるいは「願いを叶える」ならば自然に聞こえる。「叶える」の場合は活用は「叶えろ」にはなる。

文法上のことは知らないが、聞きなじみがないっていうあたりが引っ掛かるのだろう。
いつか「願いを叶え」が普通に聞こえる日が来るのかも知れないし、他の人には自然なのかも知れない。


#+begin_quote
想像力からはじまる　いま！いま！いま！

いま！いま！いま！イマジネーション
#+end_quote
っていってるから、ついつい想像力からイマジネーションがはじまるものだと思っていただけど、
想像力から「いま」がはじまるってことだった。

* 「 $1+1$ の答えは $2$ でいいの？」

** $1+1=2$ に疑問をもつ人が疑問にしないこと

 $1+1=2$ に疑問をもつ人というのは $=1$ や $=3$ ではダメなの？
決まり切った答え以外のものがあるのではないのか？
というようなことにすぎない。

数学の公式がいつでも同じ答えを出すのは、数学が真理をとりあつかっているからであり、しかも普遍的なレベルでとりあつかっているのだから、たとえば、1つの粘土と1つの粘土を合わせても1つの粘土にしかならない、というような反論は問題外であるというべき。
決まり切ってるということを杓子定規だと否定的にとらえる風潮があるけれども、科学にとってはそれは肯定性である。しかも常に誤差に悩まされる他の自然諸科学とは異なって数学の等式に誤差はない。

1個のリンゴと1個のみかんを合わせていくつ？という問題に「足せない…」と困る小学生の事例を出す場合もあるが、数の概念は極めて難しい問題である。
1とか2とか3とかをそれぞれ別ものとする流儀もあれば、1,2,3…と並んでいるとする流儀もあって、一言に「足し算」といっても寄せ集めるような流儀と並べて合わせていくような流儀との対立もある。
どちらか一方とするのは無理があるけれど、それらを統一するような概念はいまだ人類は獲得していないのである。
つまり、袋の中にりんごを加えいれて全部でいくつ、みたいに足すやり方と、経験値を得てレベルが一つずつ上がっていくように足すやり方とで「足し算」という概念もまた二つあるのである。

** 読み方
「 $1+1=2$ 」といっても読み方がいろいろ考えられる。

- 「1」+「1」

  これは前後の「1」をそれぞれ独立させてそれらを足すと見ている。とはいえ前の1と後の1を区別したりしなかったりする流儀がともにある。

- 「1」「+1」

  前の「1」に「1を加える」と見ている。この場合はいうまでもなく前の1と後の+1とは別ものである。

- 「1+1」=「2」

  これは「1+1」の和として2を見ている。いいかえれば2というのは「1+1」によって生成されているといえる。カント的に言えば分析判断。

- 「1+1=2」

  「1+1=2」をアプリオリに認める見方。カント的に言えば総合判断。

** カントの純粋理性批判
「 $5+7=12$ 」というのは分析判断なのか総合判断なのか？という問題提起。
分析判断とするならば証明可能であるけれど、前提をどうしたらいいのかが不明になる。
たとえば12の定義として「 $5+7$ 」を採用してもいいけれど、 $6+6=12$ は別の前提をもってきて証明しなければならなくなる。
$5+7$ と $6+6$ との恣意的な区別も問題になる。

総合判断とするならば証明不可能になる。前提で悩むことはなくなるけれど、前提どうしで不都合がないのかという問題が発生してくる。

** ペアノの公理系
ペアノの場合は
#+begin_quote
「 $1$ 」「 $+1$ 」 $= 1'$ (つまり $2$ )
#+end_quote
というのが基本である。

数の概念としては、 $1,2,3 \cdots$ を別ものとしながらそれらを順番に並べるというやり方をしている。
つまり1が始めにあり、 $1' =2$ が次に生まれ、 $2'=3,3'=4,4'=5 \cdots$ というように順番に生成されるものとしている。（0から始めても構わないがここでは1から始めた）

たとえば+1と+2はペアノ公理系では別ものである。
+2の場合は、+「2」であるが、+1はあくまでも「+1」である。
\begin{align*}
2+3 & =2+(2') \\
    &= (2+2)' \\
    &= (2+(1'))' \\
    &= ((2+1)')' \\
    &= ((2')')' \\
    &= ((3)')' \\
    &= (4)' \\
    &= 5
\end{align*}

のようにするのである。同じように $n+m=m+n$ も証明できるけれど自明ではない。
実は $'$ の個数という公理系外の数字が前提されているのだけれど、明示されない。

それ以外の公理系は知らない。

** 数理論理の欠陥
ところで $1+1=2$ は何と読むべきか。
英語であれば 1 plus 1 equal 2. ないしは 1 plus 1 /are/ 2. と読むのであるが、
もしもこの命題が証明されるべきものであるならば、1 plus 1 /must be/ 2. とするべきであろう。
けれども、この差異は数式において表現することはできないのである。

