#+STARTUP: indent inlineimages content
#+TITLE: 景の海のアペイリアの酷評
#+DATE: 2020-07-21
#+SETUPFILE: ~/reminder/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 
#+JEKYLL_TAGS: 
#+JEKYLL_PUBLISHED: true

* はじめに
景の海のアペイリアが評判がいいって噂を聞いてちょっと試してみた。
期待外れというか持ち上げられてる理由がわからないレベルだったので、
つまらないと思うゆえんをあげつらおうかと。

ようするに、八つ当たりして精神の安定を図ろうということ。

もしもやってて良かったと思ってるような人や、ネタバレすんなよ！って人はブラウザバックで。

* あらさがし
** 科学的推論が大雑把
量子論に基づいているのも関係するけど、科学する心がない。
こじつけと科学的推論はまったく違うということがわかってない。

** 設定のムダ遣い
MMO という舞台を作ったのにモンスターとの戦闘がボス戦のみで、ゲームとして楽しそうじゃない。
PvP がメインって思っているのかも知れないけど、戦闘というかただの舌戦。そういうのが好まれる風潮があるのは知っているけど。

サキガケ⇒ジェネレーション！みたいにゲームとして魅力があるといいのに。（八つ当たりポイント）

戦闘が単調すぎるのも困る（舌戦以外で）。
射精で最強に！っていうのはネタとしては面白いけど、技の撃ち合いしかしていないからマンネリになる。
デザイアは条件さえ満たせば途中で変えられるってなってたわりに、主人公以外は変えてない。
支払うコストによって威力が変わる状況のバリエーションを増やすのにあまり生かせていない。
アニメだったら動きで魅せることもできるけど紙芝居じゃそれもできない。
けれど、文字だけしかない小説だろうと紙芝居だろうと魅せる戦闘シーンは存在するし、作家の力量のせいじゃないかと思っている。
ついでに絆いろめく恋いろはみたいなラノベチックなやつもどうにも戦闘がショボい。（八つ当たりポイント）

ゲームでの死は現実での死を意味する！——っていうSAO的な設定をしたけどタイムリープするせいで、緊張感が台無し。
むしろ死んでもどうせ繰り返すんでしょ、っていう邪推しかできなくなった。
七海にいたっては現実で死んでるのにゲームにログインしているっていう……謎を残したかったんだろうけど、死が軽く扱われすぎている。
死はある特定の瞬間ではなくて、痛かったり苦しかったりするような一つの過程なのに、ゲーム画面で自分のキャラクターが死ぬくらいにしか想像していないのだろう。
もっとも主人公にいたっては即死攻撃を受けても自己蘇生とかするからなおさら緊張感なんてものはない。
HPっていう数字が上下してるだけってそれゲームとしても楽しいの？


** 特異点とかいう流行の軽薄さ(八つ当たりポイント)
特異点はホーキング先生が唱えたのもあって流行っているけど、厨二病患者の妄言と同じレベル。

「強いAIが誕生してしまったら人類はAIに支配されてしまうかも知れない！！」

っていうのは邪気眼系の厨二病患者がよくいっているのと同じ。

「世界最強の魔法使いになっちゃったら、世界滅ぼしちゃうかも……やべえな」

っていう妄想と対して変わらないので、特異点がどうのといってる人は厨二病患者に対するのと同じように生暖かい目で見守ってあげるのがいいと個人的には思ってる。
ホーキング先生を厨二病患者扱いしているわけではないんだけど。

まあそれはともかく、
特異点に期待を寄せる人たちというのは、現代科学の停滞堕落っぷりを誰かが突破してくれないかって他力本願的に期待しているだけであって、自分たちの無能っぷりをさらけだしている以上のものではない。
人間の頭脳活動ないし意識的活動がコンピュータのそれと同じだとみなした上で、コンピュータ上で人間の意識を再現できなくて困っている。
意識の法則が物理法則に還元できないか、というのは歴史的に何度も提出されては破棄されてきたような機械的唯物論の一種でしかない。
意識は「物質の最高の所産たる脳髄の産物」ではあるけれど、単なる物理的過程に——例えば単なる電気信号などに——還元できないという矛盾を、解決することなしには意識を生み出すなどというのは100年早い。

AIが意識をもつ場合は人間と異なってAIは集合体で個ではない、っていう見解を出す人がたまにいるけど（バルドみたいに）、
理解できない他者がいないかぎり言語表現によって他者との相互理解するってことにはならないと思うんだけど、
誰がそんな愚かな主張をしているのかよくわからない。

このゲームのように偶然意識をもったAIが生まれる、という可能性は人間が偶然意識をもったのと同じくらいにはあるのかも知れない。
（コンピュータが人間の脳髄と同じような機能をもつならば形式的可能性としてあるだろう。）
けれども人間が意識を獲得するまでには気の遠くなるような年月が必要だったのと同様にコンピュータ上で意識が偶然発生するには100年や200年ではとうてい足りないだろう。
ついでにいえば、コンピュータを人間の脳と同じ働きをするとみなしているのに、処理速度や記憶容量を無限に増やすことができて人間よりも高性能にできると期待をよせるのは、
ムシがよすぎるのではないか。

どちらにしろ人間の意識について掘り下げないかぎり、厨二病的妄想の域を脱することはない。
AIが心を持ちうるか、みたいな形で問いかけているけれど、心は意識とは視角が違うので解決しようがない。
人間の特有なるもの・物や生"物"にはないものは精神・意識・心などと規定されてきたものの、心のように時と場合・あるいは気分によって移り変わるものをあえて問題にしているのは、法則的把握を最初から放棄しているからである。
決定論的立場からすれば、精神の法則は必然的に発生せざるをえないが、それが心と呼べるかどうかはまた別ということも可能ではある。

暗黒の中世において錬金術師たちが賢者の石やホムンクルスを追い求めたのと同断の願望が特異点に期待を寄せる人たちにはある。
けれども、近代科学は両者を否定するところから始まったのであり、現代科学に対するブレイクスルーもまた似たようなところにあるのではないかと思う。
