#+TITLE: Google Keep を使ってGTD
#+DATE: 2020-03-09
#+SETUPFILE: ~/reminder/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 
#+JEKYLL_TAGS: 
#+JEKYLL_PUBLISHED: true

* GTD

ちなみに、アレンの本はまだ読んでないので間違った知識があるかも知れないけどそれは気にしない方向で！

GTD(Good Things Done)とは何かっていうと、
例えば、朝家を出たときにゴミを出して、9時から会議があって、13時からアポがあって、20時から友人と飲んで、帰宅前にコンビニに寄って買い物……
みたいな予定があったときに全部覚えておくのは大変ですよね？
次に何をしなきゃいけないと思いながら作業しておいたりすると、目の前の作業に集中できなくなりますよね？
会議中にゴミを出し忘れた！ とか思い出してもムダですし、目の前の作業のジャマにしかなりません。

なのでメモ帳やらカレンダーやら何らかのツールに全部記録して、自分の脳では覚えないようにしちゃえっていうことです。
（わりと極端にいっていますが）

GTDツールは何を使ってもいいらしいです。
むしろ自分が使いやすいものを使うべきとかいわれているみたいです（よく知らない）。
多分メモ帳とかを上手く使うのが一番便利な気はするんですが、
スマホでスタイリッシュにやると格好いいような気がする（どうでもいい理由だった）。

GTDツールは専用のものがあったりするらしいけど、使ったことがないので気になる人はググってください（人任せ）。
[[https://www.evernote.com/][Evernote]]とか使ってるのでEvernote使えよって意見もあるようですが、それはそれこれはこれ。
[[https://keep.google.com][Google Keep]]使ってみたらいい感じになりそうな予感がしたので、ちょっとやってみました。

ただKeepはいまいち流行ってないのか使い方指南、みたいなサイトがあまりないような気がする。
メモアプリを活用してるぜ！って人がいないだけかとも思う。

** GTDの流れ

1. 自分の頭の中で思い付いたこと、人からやっといて、ってとか何でもかんでもとりあえず、INBOXに入れる。
2. 行動が不要なもの→DOCUMENT,SOMEDAY、ゴミ→TRUSHへ
3. 1つの行動で終わらない→PROJECTにして1つの行動へと分ける。
4. 行動が必要なもので、2分以内に終わるものはすぐやる。
5. 2分以内に終わらないもので、他人に任せられるもの→WAIT、特定の日にやるべきこと→カレンダーに登録、それ以外はTODOへ


- INBOX :: 一時保管庫
- TODO :: 「次にやるべきことのリスト」
- WAIT :: 「他人からの連絡待ちのリスト」
- SOMEDAY :: 「いつかやる（多分やる）ことのリスト」
- DOCUMENT :: 「資料」
- PROJECT :: 1つの行動をあらわすTASKのリスト

[[https://www.itmedia.co.jp/bizid/spv/0606/28/news097_3.html]]
とか見た方が早いと思います。

* Keepを使う

ちなみに自分の場合は、Evernoteにデジタル資料を集約してるのでKeepには入れてません。
PDFとかWordファイルとかKeepだとどういう扱いになるのか知らないんですが、Google Driveにでも入れておいてリンクを貼っておけばいいんじゃないでしょうか？

おそらくGoogleの発想なので、探すときは検索しろよってことなのでしょう。
フォルダ的なものはないのでいっぱいあると探すのが大変になる気がしていますが、
+Evernoteでうまくやれてるので今更考えるのが面倒になってる+
タグを使うといい感じにはできるとは思います。

** INBOXはピン止め

実はKeepで困ったのはINBOXがないという問題です。
INBOXはゴチャゴチャしてない整理したときの快感がないので、とりあえずINBOXにモノがあると自分にストレスがたまるような感じにしたい（偏見）

ちょっと手間なんですが、メモを新規に作ったときは必ずピンをつけるようにします。
- INBOXから出す＝ピンを外す
というルールです。

** タグで分類
「@TODO」、「@WAIT」、「@SOMEDAY」「@DONE」
のタグをつくっておきます。
最初に@をつけておいて他のタグと区別できるようにしておくと便利です。

- いつかやること→ @SOMEDAY
- 他人に任せる→ @WAIT
- 次にやるべきこと→ @TODO
- 完了したもの→ @TODO

@TODOや@WAITなどは終わったら@DONEタグに変更する。

** リマインダー
特定の日付にやるようなことは、リマインダーをつけます。
これをやっておくとGoogleカレンダーに自動で登録されるので便利だったりします。
ちなみにカレンダー上で動かすことできます。

GTDからすると間違ってるんですが、WAITを使ってないのでリマインダーを設定したものにWAITタグをつけてます。
何もタグがついてないのがちょっと気持ち悪かったので（@REMINDER とか作ればいいだけの話）

** 色づけで分類
Chromeの拡張機能で [[https://chrome.google.com/webstore/detail/dlahcjmefibiedeecoegjilekaebchhl][Category Tabs for Google Keep]] とかを使うと色に名前を付けられて便利です。
+アプリでも使えるようになってくれたらうれしいなあ+

たとえば
- オレンジ→仕事
- 黄色→趣味
- 緑→買い物
- 水色→学びたいこと

みたいな自分ルールを作って色をつけていきます。

Androidアプリの場合は上の「メモを検索」ってところを選ぶと下の方に色っていうのがあるので、
色を選ぶとその色のメモだけ表示されるようになります。

単に見た目の問題だけでなく検索性も上がります。

** PROJECTもタグを使う
プロジェクトリストはタグで表現します。
「日付+タイトル」の形式にしておくと後で見返すときに探しやすいと思います。

たとえば今日のブログのネタのために集めていたメモがあれば
「200309ブログ」というタグをつけておくとよいでしょう。

ちなみにチェックボックスを使うのが通常のプロジェクトリストにはなると思いますが、
1タスク1メモの方が便利な場合もあると思われるので、どっちも使うといいでしょう。

** 資料(DOCUMENT)にもタグ
仕事に使う資料には「#WORK」とか
勉強することには「#STUDY」とか
そんなタグをつけておくとプロジェクトに入っていないものも網羅できると思います。

色づけと役割はかぶるんですが、アプリ版だとタグの方が便利だってことにあとから気づいたせい……。

** WAIT
他人に任せることはそのままメモを「送信」ってやると送れるみたいです
（使ったことがないので、ドキュメントとかリンクとかメールとかどういうのがいいのかわかりません）

** 日次・週次レビューでやること
- INBOX（ピン止め）に何かあればタグをつけて色をつける。（本当はレビュー時にやることじゃない……）
- @DONE がこれまでに終わったことなのでレビューする。レビューが終わったらアーカイブする。
- チェックボックスにしてあるものはアーカイブするときにチェックボックスを全部外すと後で見やすくなる。
- @SOMEDAYながめてみて、@TODOにできるものは変更する。

レビューって何をやればいいのかそんなにわかってないのですが、
アーカイブするとか、タグ変えるとかそういう行動があるとちょっとはレビューがはかどるんじゃないかと思っている。
内容はそのうち高度になっていく予定。
