#+TITLE: 問題なのは読解力か問題文か
#+DATE: 2020-01-02
#+SETUPFILE: ~/reminder/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 
#+JEKYLL_TAGS: 
#+JEKYLL_PUBLISHED: true

* 問題なのは読解力か問題文か

[[https://leemanparadise.com/neta/reading-skill/][子どもたちの学力がヤバいのは「読解力」欠如のせいだった]]
を何となく見てたんだけど、
子供の読解力が問題なのか、はたまた問題文がヘタクソすぎるのか悩ましく思えた。

ちなみにブログの主張は総スルーしてるのでタイトルが煽りに見えるかも知れないが、タイトルと内容が合ってる？
とは思ったが特に他意はない。

** ちょっとした違い

- 「美しい水車小屋の乙女」

という例があったけれど（これはおそらくドイツ語からの直訳なのだろう）、

- 「水車小屋の美しい乙女」

と書いてくれさえすればどの語がどこ語を形容しているのかとわざわざ考える必要はない。

* "ひっかけ"問題
** カテゴリー（用語）の意味を知っているか？ という発想
#+begin_quote
次の文章を読み、（　）に入る語の番号を答えなさい。
- アミラーゼという酵素はグルコースがつながってできたデンプンを分解するが、同じグルコースからできていても、形が違うセルロースは分解できない。
- セルロースは（　　）と形が違う。
  1. デンプン
  1. アミラーゼ
  1. グルコース
  1. 酵素
#+HTML: <cite>（出典:東京書籍・高校生物基礎教科書）</cite>
#+end_quote
この問題は、セルロースとデンプンがグルコースからできているということを知っていれば問題文を読むまでもなく回答できる。

知らなくても問題文をちゃんと読めば回答はできることはできる。
だから"知識"ではなく"読解"問題なのだとは思う。

** 入試で点を落とさせるために"ひっかける"

こういう問題文になるのに理由はある。
入試問題が点を取らせるのではなく点を落とさせる、という発想で作られているからである。

素直に読むと素直に回答できる、では問題にはならない。
ゴチャゴチャした文を読んで正答できる人は確かに"読解力がある"と評価できるだろう。

けれども、正答した人が必ずしも読解力があるとは言えないのではないか？
セルロースについての知識がある人だって正答できるだろうから。

学力よりも注意力をみているかのよう。

** これを子供がマネしていいのか？
日常的に触れる文章がこういうものであった場合、子供も同じような文章を書くようにしかならない。

「教科書」である以上、お手本になるような文章を心掛けるべきだ。
今回のブログで紹介されていた教科書を見ていて思った。

* RSTテスト（読解力テスト）とかいうもの
モロに足を出して"ひっかかるなよ"、といっているような不快な問題（例がヘタクソだけど）

#+begin_quote
- 「メジャーリーグの選手のうち28%はアメリカ合衆国以外の出身の選手であるが、その出身国を見るとドミニカ共和国が最も多くおよそ35%である」
- 「Alexは男性にも女性にも使われる名前で、女性の名Alexandraの愛称であるが、男性の名Alexanderの愛称でもある」。「Alexandraの愛称は（　　）である」。
#+end_quote
という例題が引用されている。（ざっくりとした引用なので元ページ参照）

どこをどうひっかけたいのかまでミエミエなのも気にくわないし、文章も気にくわない。
- メジャーリーグが米国野球のことだって説明がないのに「アメリカ合衆国」とかいう名称を使っているあたりとか。（新聞では文字数節約のために「米国」表記が多いと思われる。日常では「アメリカ」ぐらいの表現の方が多いハズ。）
- 「〜が、」「〜と、」「〜で、」とかいう接続詞の選び方が乱雑で読みにくい。

もうちょっと生徒にどういう文章を書かせたいのかを意識して教科書（問題文）の文章を書いてくれないものか。

** 文章が読めないのは問題
文章が読めないのは問題だ。

一定程度の深さを持つ内容を論じるには一定の長さの文章が必要になるので、
"わかりにくい"文章であろうと読めるべきではある。
"読解"が必要になることはある。

とはいえ、特に必要もないのにヘンな文章にして"さあ読んでみろ"とするのではなく、
小論文のようなものから著者は何を言いたいのか、主張の根拠は何か、主張を正当化するためにどのような論理を駆使しているのか、
といったようなことを読み取らせるべきではないのか。

そんなことを言っていたら、"長文読解は別にある"とかそんなことを言われそうな気もするけれど、
ヘンな問題文を出していいことにはならない。

読解は、たとえゴチャゴチャした論理展開であろうと、相手の言いたいことを"読み解く"ものだと思う。
重箱のスミをつついて相手を攻撃するためではなく、理解するために推理するのではないか。
そういう意味では上で挙げられていた例は、問題が文章の主題と関係のないところに設定されている。
